# Generated by Django 4.0.3 on 2022-06-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Action',
        ),
    ]
